# Generated by Django 4.0.2 on 2022-03-11 18:27

import banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbanner',
            name='is_active',
            field=models.BooleanField(default=False, validators=[banners.models.validate_active_status], verbose_name='Aktywny'),
        ),
    ]
