# Generated by Django 4.0.2 on 2022-03-04 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytuł', models.CharField(help_text='Krótki tytuł', max_length=25, unique=True, verbose_name='Tytuł')),
                ('link', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Link')),
                ('obraz', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/', verbose_name='Obraz')),
                ('obraz_opis', models.CharField(help_text='Alt Description for Photo', max_length=100, verbose_name='Obraz opis')),
                ('dodano', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('zaktualizowano', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('dodane_przez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dodane przez')),
            ],
            options={
                'ordering': ('-dodano',),
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('posts', models.ManyToManyField(to='gallery.ImagePost', verbose_name='Posts')),
            ],
            options={
                'verbose_name_plural': 'ImageGalleries',
                'ordering': ('-created',),
            },
        ),
    ]
