# Generated by Django 4.0.2 on 2022-03-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='użyty_w_galerii',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Użyty w galerii:'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='użyty',
            field=models.BooleanField(default=False, verbose_name='Użyty'),
        ),
    ]
