# Generated by Django 4.0.2 on 2022-03-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='obraz_opis',
            field=models.CharField(help_text='Alt opis dla zdjęcia', max_length=100, verbose_name='Obraz opis'),
        ),
    ]
