# Generated by Django 4.0.2 on 2022-03-08 18:52

from django.db import migrations, models
import functools
import gallery.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='obraz',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(gallery.utils._update_filename, *(), **{'path': 'images/'}), verbose_name='Obraz'),
        ),
    ]
