# Generated by Django 4.0.2 on 2022-03-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='link',
            new_name='slug',
        ),
    ]
