# Generated by Django 4.0.2 on 2022-03-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.CharField(blank=True, help_text='Automatycznie generowany', max_length=100, null=True, unique=True, verbose_name='Link'),
        ),
    ]
