# Generated by Django 4.0.2 on 2022-03-08 18:53

from django.db import migrations, models
import django.db.models.deletion
import functools
import gallery.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_imagepost_obraz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='główne_zdjęcie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image', to='gallery.imagepost', verbose_name='Główne zdjęcie'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='obraz',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=functools.partial(gallery.utils._update_filename, *(), **{'path': 'images/'}), verbose_name='Obraz'),
        ),
    ]
