# Generated by Django 4.0.2 on 2022-02-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name', max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, help_text='Phone number', max_digits=12)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('model', models.CharField(help_text='Model', max_length=50)),
                ('comment', models.TextField(help_text='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
