# Generated by Django 4.0.2 on 2022-03-04 17:07

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=12, validators=[orders.models.phone_number_validator])),
                ('email', models.EmailField(max_length=254)),
                ('model', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
