# Generated by Django 4.0.2 on 2022-03-27 10:09

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imię_i_nazwisko', models.CharField(max_length=50, validators=[core.validators.fullname_validator], verbose_name='Imię i Nazwisko')),
                ('numer_telefonu', models.CharField(max_length=20, validators=[core.validators.phone_number_validator], verbose_name='Numer telefonu')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('komentarz', models.TextField(blank=True, null=True, verbose_name='Komentarz')),
                ('dodano', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('zaktualizowano', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'ordering': ('-dodano',),
            },
        ),
    ]
