# Generated by Django 4.0.2 on 2022-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='imię_i_nazwisko',
            field=models.CharField(max_length=50, verbose_name='Imię i Nazwisko'),
        ),
    ]
