# Generated by Django 4.0.2 on 2022-03-13 16:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_imię_i_nazwisko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='imię_i_nazwisko',
            field=models.CharField(max_length=50, validators=[core.validators.fullname_validator], verbose_name='Imię i Nazwisko'),
        ),
    ]
