# Generated by Django 4.0.2 on 2022-03-03 14:11

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_comment_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[orders.models.phone_number_validator]),
        ),
    ]
